package dev.akarah.dimension;
import dev.akarah.datatypes.server.Identifier;
import dev.akarah.item.Item;
import dev.akarah.dimension.Dimension;
import dev.akarah.entities.EntityType;
import dev.akarah.dimension.BlockType;
//This code is autogenerated.
//Do not modify this code.
class BuiltInDimensions {    public static Identifier<Dimension> OVERWORLD = Identifier.<Dimension>of("minecraft:overworld");
    public static Identifier<Dimension> THE_NETHER = Identifier.<Dimension>of("minecraft:the_nether");
    public static Identifier<Dimension> THE_END = Identifier.<Dimension>of("minecraft:the_end");}