package dev.akarah.dimension;
import dev.akarah.datatypes.server.Identifier;

//This code is autogenerated.
//Do not modify this code.
public class BuiltInDimensions {    public static Identifier<Dimension> OVERWORLD = Identifier.<Dimension>of("minecraft:overworld");
    public static Identifier<Dimension> THE_END = Identifier.<Dimension>of("minecraft:the_end");
    public static Identifier<Dimension> THE_NETHER = Identifier.<Dimension>of("minecraft:the_nether");}